version: '3.1'

services:

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbit-processador-arquivos
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq]
    environment:
      - RABBITMQ_DEFAULT_USER= wall@btg
      - RABBITMQ_DEFAULT_PASS= teste